export const hotMovies = {
  trendingWeek: {
    movies: [
      {
        backdrop_path: undefined,
        id: 693134,
        original_title: "Dune: Part Two",
        overview:
          "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Dune: Part Two",
        original_language: "en",
        genre_ids: [878, 12],
        popularity: 1990.512,
        release_date: "2024-02-27",
        video: false,
        vote_average: 8.265,
        vote_count: 3444,
      },
      {
        backdrop_path: undefined,
        id: 934632,
        original_title: "Rebel Moon — Part Two: The Scargiver",
        overview:
          "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Rebel Moon — Part Two: The Scargiver",
        original_language: "en",
        genre_ids: [878, 28, 18, 12],
        popularity: 2477.048,
        release_date: "2024-04-19",
        video: false,
        vote_average: 6.1,
        vote_count: 536,
      },
      {
        backdrop_path: undefined,
        id: 560016,
        original_title: "Monkey Man",
        overview:
          "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Monkey Man",
        original_language: "en",
        genre_ids: [28, 53, 80],
        popularity: 502.284,
        release_date: "2024-04-03",
        video: false,
        vote_average: 7.273,
        vote_count: 251,
      },
      {
        backdrop_path: undefined,
        id: 438631,
        original_title: "Dune",
        overview:
          "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Dune",
        original_language: "en",
        genre_ids: [878, 12],
        popularity: 627.288,
        release_date: "2021-09-15",
        video: false,
        vote_average: 7.79,
        vote_count: 11430,
      },
      {
        backdrop_path: undefined,
        id: 929590,
        original_title: "Civil War",
        overview:
          "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Civil War",
        original_language: "en",
        genre_ids: [10752, 28, 18],
        popularity: 723.121,
        release_date: "2024-04-10",
        video: false,
        vote_average: 7.402,
        vote_count: 473,
      },
      {
        backdrop_path: undefined,
        id: 1011985,
        original_title: "Kung Fu Panda 4",
        overview:
          "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Kung Fu Panda 4",
        original_language: "en",
        genre_ids: [16, 28, 10751, 35, 14],
        popularity: 2020.311,
        release_date: "2024-03-02",
        video: false,
        vote_average: 7.2,
        vote_count: 1374,
      },
      {
        backdrop_path: undefined,
        id: 937287,
        original_title: "Challengers",
        overview:
          'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Challengers",
        original_language: "en",
        genre_ids: [18, 10749],
        popularity: 531.851,
        release_date: "2024-04-18",
        video: false,
        vote_average: 7.402,
        vote_count: 174,
      },
      {
        backdrop_path: undefined,
        id: 967847,
        original_title: "Ghostbusters: Frozen Empire",
        overview:
          "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Ghostbusters: Frozen Empire",
        original_language: "en",
        genre_ids: [14, 12, 35],
        popularity: 425.019,
        release_date: "2024-03-20",
        video: false,
        vote_average: 6.406,
        vote_count: 347,
      },
      {
        backdrop_path: undefined,
        id: 838209,
        original_title: "파묘",
        overview:
          "After tracing the origin of a disturbing supernatural affliction to a wealthy family's ancestral gravesite, a team of paranormal experts relocates the remains—and soon discovers what happens to those who dare to mess with the wrong grave.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Exhuma",
        original_language: "ko",
        genre_ids: [9648, 27, 53],
        popularity: 367.942,
        release_date: "2024-02-22",
        video: false,
        vote_average: 7.8,
        vote_count: 56,
      },
      {
        backdrop_path: undefined,
        id: 866398,
        original_title: "The Beekeeper",
        overview:
          "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "The Beekeeper",
        original_language: "en",
        genre_ids: [28, 53, 18],
        popularity: 458.009,
        release_date: "2024-01-08",
        video: false,
        vote_average: 7.458,
        vote_count: 2176,
      },
      {
        backdrop_path: undefined,
        id: 618588,
        original_title: "Arthur the King",
        overview:
          "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Arthur the King",
        original_language: "en",
        genre_ids: [18, 12],
        popularity: 1308.397,
        release_date: "2024-03-15",
        video: false,
        vote_average: 6.762,
        vote_count: 65,
      },
      {
        backdrop_path: undefined,
        id: 1041613,
        original_title: "Immaculate",
        overview:
          "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Immaculate",
        original_language: "en",
        genre_ids: [27, 9648, 53],
        popularity: 1542.821,
        release_date: "2024-03-20",
        video: false,
        vote_average: 6.234,
        vote_count: 310,
      },
      {
        backdrop_path: undefined,
        id: 938614,
        original_title: "Late Night with the Devil",
        overview:
          "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Late Night with the Devil",
        original_language: "en",
        genre_ids: [27],
        popularity: 810.306,
        release_date: "2024-03-19",
        video: false,
        vote_average: 7.319,
        vote_count: 240,
      },
      {
        backdrop_path: undefined,
        id: 948549,
        original_title: "Love Lies Bleeding",
        overview:
          "Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Love Lies Bleeding",
        original_language: "en",
        genre_ids: [80, 10749, 53],
        popularity: 243.412,
        release_date: "2024-03-08",
        video: false,
        vote_average: 7.145,
        vote_count: 83,
      },
      {
        backdrop_path: undefined,
        id: 823464,
        original_title: "Godzilla x Kong: The New Empire",
        overview:
          "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Godzilla x Kong: The New Empire",
        original_language: "en",
        genre_ids: [28, 878, 12],
        popularity: 2372.572,
        release_date: "2024-03-27",
        video: false,
        vote_average: 6.65,
        vote_count: 792,
      },
      {
        backdrop_path: undefined,
        id: 845111,
        original_title: "Les trois mousquetaires : Milady",
        overview:
          "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "The Three Musketeers: Milady",
        original_language: "fr",
        genre_ids: [12, 28, 18],
        popularity: 1352.91,
        release_date: "2023-12-13",
        video: false,
        vote_average: 6.531,
        vote_count: 343,
      },
      {
        backdrop_path: undefined,
        id: 848326,
        original_title: "Rebel Moon — Part One: A Child of Fire",
        overview:
          "When the ruthless forces of the Motherworld threaten a quiet farming village on a distant moon, a mysterious outsider becomes its best hope for survival.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Rebel Moon — Part One: A Child of Fire",
        original_language: "en",
        genre_ids: [878, 18, 28],
        popularity: 349.153,
        release_date: "2023-12-15",
        video: false,
        vote_average: 6.372,
        vote_count: 1754,
      },
      {
        backdrop_path: undefined,
        id: 1209288,
        original_title: "Justice League: Crisis on Infinite Earths Part Two",
        overview:
          "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Justice League: Crisis on Infinite Earths Part Two",
        original_language: "en",
        genre_ids: [16, 878, 28],
        popularity: 790.506,
        release_date: "2024-04-22",
        video: false,
        vote_average: 6.091,
        vote_count: 33,
      },
      {
        backdrop_path: undefined,
        id: 1111873,
        original_title: "Abigail",
        overview:
          "After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.",
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Abigail",
        original_language: "en",
        genre_ids: [27, 53, 35],
        popularity: 441.785,
        release_date: "2024-04-18",
        video: false,
        vote_average: 6.861,
        vote_count: 72,
      },
      {
        backdrop_path: undefined,
        id: 533535,
        original_title: "Deadpool & Wolverine",
        overview: 'Third entry in the "Deadpool" franchise. Plot TBA.',
        poster_path: undefined,
        media_type: "movie",
        adult: false,
        title: "Deadpool & Wolverine",
        original_language: "en",
        genre_ids: [35, 878, 28],
        popularity: 362.026,
        release_date: "2024-07-24",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
    ],
    shows: [
      {
        backdrop_path: undefined,
        id: 106379,
        original_name: "Fallout",
        overview:
          "The story of haves and have-nots in a world in which there’s almost nothing left to have. 200 years after the apocalypse, the gentle denizens of luxury fallout shelters are forced to return to the irradiated hellscape their ancestors left behind — and are shocked to discover an incredibly complex, gleefully weird, and highly violent universe waiting for them.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Fallout",
        original_language: "en",
        genre_ids: [10759, 10765, 9648],
        popularity: 2102.173,
        first_air_date: "2024-04-10",
        vote_average: 8.413,
        vote_count: 733,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 126308,
        original_name: "Shōgun",
        overview:
          "In Japan in the year 1600, at the dawn of a century-defining civil war, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Shōgun",
        original_language: "en",
        genre_ids: [18, 10768],
        popularity: 1880.694,
        first_air_date: "2024-02-27",
        vote_average: 8.591,
        vote_count: 594,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 158300,
        original_name: "Knuckles",
        overview:
          "Knuckles embarks on a hilarious and action-packed journey of self-discovery as he agrees to train Wade as his protégé and teach him the ways of the Echidna warrior.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Knuckles",
        original_language: "en",
        genre_ids: [10759, 10751, 35],
        popularity: 367.986,
        first_air_date: "2024-04-26",
        vote_average: 8.2,
        vote_count: 68,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 37854,
        original_name: "ワンピース",
        overview:
          'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "One Piece",
        original_language: "ja",
        genre_ids: [10759, 35, 16],
        popularity: 181.572,
        first_air_date: "1999-10-20",
        vote_average: 8.7,
        vote_count: 4417,
        origin_country: ["JP"],
      },
      {
        backdrop_path: undefined,
        id: 241259,
        original_name: "Baby Reindeer",
        overview:
          "When a struggling comedian shows one act of kindness to a vulnerable woman, it sparks a suffocating obsession which threatens to wreck both their lives.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Baby Reindeer",
        original_language: "en",
        genre_ids: [18],
        popularity: 982.563,
        first_air_date: "2024-04-11",
        vote_average: 8.065,
        vote_count: 130,
        origin_country: ["GB"],
      },
      {
        backdrop_path: undefined,
        id: 132750,
        original_name: "Dead Boy Detectives",
        overview:
          "Two teen ghosts work alongside a clairvoyant to solve mysteries for their supernatural clientele — until a powerful witch complicates their plans.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Dead Boy Detectives",
        original_language: "en",
        genre_ids: [18, 9648, 10765],
        popularity: 368.22,
        first_air_date: "2024-04-25",
        vote_average: 7.358,
        vote_count: 53,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 108545,
        original_name: "3 Body Problem",
        overview:
          "Across continents and decades, five brilliant friends make earth-shattering discoveries as the laws of science unravel and an existential threat emerges.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "3 Body Problem",
        original_language: "en",
        genre_ids: [10765, 9648, 18],
        popularity: 541.503,
        first_air_date: "2024-03-21",
        vote_average: 7.523,
        vote_count: 598,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 139547,
        original_name: "종말의 바보",
        overview:
          "As an asteroid hurtles towards Earth with nothing to stop it, one determined teacher fights to keep her former students safe — no matter the cost.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Goodbye Earth",
        original_language: "ko",
        genre_ids: [18],
        popularity: 229.662,
        first_air_date: "2024-04-26",
        vote_average: 6.444,
        vote_count: 9,
        origin_country: ["KR"],
      },
      {
        backdrop_path: undefined,
        id: 138502,
        original_name: "X-Men '97",
        overview:
          "The X-Men, a band of mutants who use their uncanny gifts to protect a world that hates and fears them, are challenged like never before, forced to face a dangerous and unexpected new future.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "X-Men '97",
        original_language: "en",
        genre_ids: [16, 10759, 10765],
        popularity: 877.111,
        first_air_date: "2024-03-20",
        vote_average: 8.726,
        vote_count: 179,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 82684,
        original_name: "転生したらスライムだった件",
        overview:
          "37-year-old corporate worker Mikami Satoru is stabbed by a random killer, and is reborn to an alternate world. But he turns out to be reborn a slime! Thrown into this new world with the name Rimuru Tempest, he begins his quest to create a world that’s welcoming to all races. Broken free from ordinary, stale past life, his fresh adventure in a fantasy world as a slime monster with unique abilities begins.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "That Time I Got Reincarnated as a Slime",
        original_language: "ja",
        genre_ids: [10759, 16, 10765, 35],
        popularity: 222.465,
        first_air_date: "2018-10-02",
        vote_average: 8.5,
        vote_count: 703,
        origin_country: ["JP"],
      },
      {
        backdrop_path: undefined,
        id: 208825,
        original_name: "기생수: 더 그레이",
        overview:
          "When unidentified parasites violently take over human hosts and gain power, humanity must rise to combat the growing threat.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Parasyte: The Grey",
        original_language: "ko",
        genre_ids: [10765, 10759, 18],
        popularity: 318.673,
        first_air_date: "2024-04-05",
        vote_average: 7.634,
        vote_count: 116,
        origin_country: ["KR"],
      },
      {
        backdrop_path: undefined,
        id: 215720,
        original_name: "눈물의 여왕",
        overview:
          "The queen of department stores and the prince of supermarkets weather a marital crisis—until love miraculously begins to bloom again.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Queen of Tears",
        original_language: "ko",
        genre_ids: [18, 35],
        popularity: 593.029,
        first_air_date: "2024-03-09",
        vote_average: 8.7,
        vote_count: 33,
        origin_country: ["KR"],
      },
      {
        backdrop_path: undefined,
        id: 120462,
        original_name: "Them",
        overview: "A limited anthology series that explores terror in America.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Them",
        original_language: "en",
        genre_ids: [18, 9648],
        popularity: 293.634,
        first_air_date: "2021-04-09",
        vote_average: 7.6,
        vote_count: 332,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 203744,
        original_name: "Sugar",
        overview:
          "An enigmatic private detective struggles with personal demons as he investigates the disappearance of a Hollywood producer's beloved granddaughter.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Sugar",
        original_language: "en",
        genre_ids: [18, 9648],
        popularity: 390.462,
        first_air_date: "2024-04-04",
        vote_average: 7.9,
        vote_count: 25,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 1399,
        original_name: "Game of Thrones",
        overview:
          "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Game of Thrones",
        original_language: "en",
        genre_ids: [10765, 18, 10759],
        popularity: 2266.725,
        first_air_date: "2011-04-17",
        vote_average: 8.449,
        vote_count: 23040,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 67198,
        original_name: "Star Trek: Discovery",
        overview:
          "Follow the voyages of Starfleet on their missions to discover new worlds and new life forms, and one Starfleet officer who must learn that to truly understand all things alien, you must first understand yourself.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Star Trek: Discovery",
        original_language: "en",
        genre_ids: [10765, 10759, 18],
        popularity: 1297.458,
        first_air_date: "2017-09-24",
        vote_average: 7.129,
        vote_count: 1662,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 1429,
        original_name: "進撃の巨人",
        overview:
          "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Attack on Titan",
        original_language: "ja",
        genre_ids: [16, 10765, 10759],
        popularity: 234.212,
        first_air_date: "2013-04-07",
        vote_average: 8.664,
        vote_count: 6025,
        origin_country: ["JP"],
      },
      {
        backdrop_path: undefined,
        id: 207468,
        original_name: "怪獣８号",
        overview:
          "In a world plagued by creatures known as Kaiju, Kafka Hibino aspired to enlist in The Defense Force. He makes a promise to enlist with his childhood friend, Mina Ashiro. Soon, life takes them in separate ways. While employed cleaning up after Kaiju battles, Kafka meets Reno Ichikawa. Reno's determination to join The Defense Force reawakens Kafka's promise to join Mina and protect humanity.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Kaiju No. 8",
        original_language: "ja",
        genre_ids: [16, 10759, 10765],
        popularity: 1008.001,
        first_air_date: "2024-04-13",
        vote_average: 8.512,
        vote_count: 41,
        origin_country: ["JP"],
      },
      {
        backdrop_path: undefined,
        id: 129398,
        original_name: "The Sympathizer",
        overview:
          "An espionage thriller and cross-culture satire about the struggles of a half-French, half-Vietnamese communist spy during the final days of the Vietnam War and his resulting exile in the United States.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "The Sympathizer",
        original_language: "en",
        genre_ids: [18, 35],
        popularity: 295.134,
        first_air_date: "2024-04-14",
        vote_average: 8.6,
        vote_count: 16,
        origin_country: ["US"],
      },
      {
        backdrop_path: undefined,
        id: 94664,
        original_name: "無職転生 ～異世界行ったら本気だす～",
        overview:
          "A 34-year-old hikikomori is kicked out of his home by his family after the death of his parents. After his eviction, he saves a group of teenagers from being killed by a speeding truck, but loses his life in the process. When he comes to, he realizes he has been reborn as Rudeus Greyrat, in a world of swords and sorcery.",
        poster_path: undefined,
        media_type: "tv",
        adult: false,
        name: "Mushoku Tensei: Jobless Reincarnation",
        original_language: "ja",
        genre_ids: [16, 10759, 10765],
        popularity: 629.245,
        first_air_date: "2021-01-11",
        vote_average: 8.5,
        vote_count: 958,
        origin_country: ["JP"],
      },
    ],
  },
  topRated: {
    movies: [
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 80],
        id: 278,
        original_language: "en",
        original_title: "The Shawshank Redemption",
        overview:
          "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        popularity: 135.298,
        poster_path: undefined,
        release_date: "1994-09-23",
        title: "The Shawshank Redemption",
        video: false,
        vote_average: 8.703,
        vote_count: 26057,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 80],
        id: 238,
        original_language: "en",
        original_title: "The Godfather",
        overview:
          "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
        popularity: 149.41,
        poster_path: undefined,
        release_date: "1972-03-14",
        title: "The Godfather",
        video: false,
        vote_average: 8.695,
        vote_count: 19752,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 80],
        id: 240,
        original_language: "en",
        original_title: "The Godfather Part II",
        overview:
          "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
        popularity: 131.373,
        poster_path: undefined,
        release_date: "1974-12-20",
        title: "The Godfather Part II",
        video: false,
        vote_average: 8.577,
        vote_count: 11933,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 36, 10752],
        id: 424,
        original_language: "en",
        original_title: "Schindler's List",
        overview:
          "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
        popularity: 89.065,
        poster_path: undefined,
        release_date: "1993-12-15",
        title: "Schindler's List",
        video: false,
        vote_average: 8.568,
        vote_count: 15335,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18],
        id: 389,
        original_language: "en",
        original_title: "12 Angry Men",
        overview:
          "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
        popularity: 66.964,
        poster_path: undefined,
        release_date: "1957-04-10",
        title: "12 Angry Men",
        video: false,
        vote_average: 8.542,
        vote_count: 8207,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10751, 14],
        id: 129,
        original_language: "ja",
        original_title: "千と千尋の神隠し",
        overview:
          "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        popularity: 110.761,
        poster_path: undefined,
        release_date: "2001-07-20",
        title: "Spirited Away",
        video: false,
        vote_average: 8.538,
        vote_count: 15853,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [35, 18, 10749],
        id: 19404,
        original_language: "hi",
        original_title: "दिलवाले दुल्हनिया ले जायेंगे",
        overview:
          "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
        popularity: 37.511,
        poster_path: undefined,
        release_date: "1995-10-20",
        title: "Dilwale Dulhania Le Jayenge",
        video: false,
        vote_average: 8.536,
        vote_count: 4376,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 28, 80, 53],
        id: 155,
        original_language: "en",
        original_title: "The Dark Knight",
        overview:
          "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        popularity: 142.69,
        poster_path: undefined,
        release_date: "2008-07-16",
        title: "The Dark Knight",
        video: false,
        vote_average: 8.515,
        vote_count: 31835,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [35, 53, 18],
        id: 496243,
        original_language: "ko",
        original_title: "기생충",
        overview:
          "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        popularity: 96.508,
        poster_path: undefined,
        release_date: "2019-05-30",
        title: "Parasite",
        video: false,
        vote_average: 8.511,
        vote_count: 17465,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [14, 18, 80],
        id: 497,
        original_language: "en",
        original_title: "The Green Mile",
        overview:
          "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        popularity: 103.764,
        poster_path: undefined,
        release_date: "1999-12-10",
        title: "The Green Mile",
        video: false,
        vote_average: 8.506,
        vote_count: 16759,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10749, 18],
        id: 372058,
        original_language: "ja",
        original_title: "君の名は。",
        overview:
          "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
        popularity: 100.206,
        poster_path: undefined,
        release_date: "2016-08-26",
        title: "Your Name.",
        video: false,
        vote_average: 8.496,
        vote_count: 10937,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [53, 80],
        id: 680,
        original_language: "en",
        original_title: "Pulp Fiction",
        overview:
          "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        popularity: 365.914,
        poster_path: undefined,
        release_date: "1994-09-10",
        title: "Pulp Fiction",
        video: false,
        vote_average: 8.489,
        vote_count: 26995,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [12, 14, 28],
        id: 122,
        original_language: "en",
        original_title: "The Lord of the Rings: The Return of the King",
        overview:
          "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
        popularity: 132.597,
        poster_path: undefined,
        release_date: "2003-12-01",
        title: "The Lord of the Rings: The Return of the King",
        video: false,
        vote_average: 8.479,
        vote_count: 23314,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [35, 18, 10749],
        id: 13,
        original_language: "en",
        original_title: "Forrest Gump",
        overview:
          "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
        popularity: 206.801,
        poster_path: undefined,
        release_date: "1994-06-23",
        title: "Forrest Gump",
        video: false,
        vote_average: 8.475,
        vote_count: 26530,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [37],
        id: 429,
        original_language: "it",
        original_title: "Il buono, il brutto, il cattivo",
        overview:
          "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
        popularity: 77.262,
        poster_path: undefined,
        release_date: "1966-12-22",
        title: "The Good, the Bad and the Ugly",
        video: false,
        vote_average: 8.468,
        vote_count: 8229,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 80],
        id: 769,
        original_language: "en",
        original_title: "GoodFellas",
        overview:
          "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
        popularity: 239.698,
        poster_path: undefined,
        release_date: "1990-09-12",
        title: "GoodFellas",
        video: false,
        vote_average: 8.466,
        vote_count: 12341,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 18, 10752],
        id: 12477,
        original_language: "ja",
        original_title: "火垂るの墓",
        overview:
          "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
        popularity: 0.6,
        poster_path: undefined,
        release_date: "1988-04-16",
        title: "Grave of the Fireflies",
        video: false,
        vote_average: 8.464,
        vote_count: 5219,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 10749],
        id: 11216,
        original_language: "it",
        original_title: "Nuovo Cinema Paradiso",
        overview:
          "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
        popularity: 61.391,
        poster_path: undefined,
        release_date: "1988-11-17",
        title: "Cinema Paradiso",
        video: false,
        vote_average: 8.454,
        vote_count: 4180,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [28, 18],
        id: 346,
        original_language: "ja",
        original_title: "七人の侍",
        overview:
          "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
        popularity: 39.433,
        poster_path: undefined,
        release_date: "1954-04-26",
        title: "Seven Samurai",
        video: false,
        vote_average: 8.453,
        vote_count: 3474,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [35, 18],
        id: 637,
        original_language: "it",
        original_title: "La vita è bella",
        overview:
          "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
        popularity: 58.315,
        poster_path: undefined,
        release_date: "1997-12-20",
        title: "Life Is Beautiful",
        video: false,
        vote_average: 8.451,
        vote_count: 12686,
      },
    ],
    shows: [
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 35, 10765],
        id: 94954,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Hazbin Hotel",
        overview:
          "In attempt to find a non-violent alternative for reducing Hell's overpopulation, the daughter of Lucifer opens a rehabilitation hotel that offers a group of misfit demons a chance at redemption.",
        popularity: 357.168,
        poster_path: undefined,
        first_air_date: "2024-01-18",
        name: "Hazbin Hotel",
        vote_average: 9.024,
        vote_count: 861,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 80],
        id: 1396,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Breaking Bad",
        overview:
          "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
        popularity: 1187.936,
        poster_path: undefined,
        first_air_date: "2008-01-20",
        name: "Breaking Bad",
        vote_average: 8.908,
        vote_count: 13458,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 18, 10765, 10759],
        id: 94605,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Arcane",
        overview:
          "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
        popularity: 208.374,
        poster_path: undefined,
        first_air_date: "2021-11-06",
        name: "Arcane",
        vote_average: 8.744,
        vote_count: 3725,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [10759, 35, 16],
        id: 37854,
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "ワンピース",
        overview:
          'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
        popularity: 181.572,
        poster_path: undefined,
        first_air_date: "1999-10-20",
        name: "One Piece",
        vote_average: 8.7,
        vote_count: 4417,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10759, 10765],
        id: 246,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Avatar: The Last Airbender",
        overview:
          "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
        popularity: 425.103,
        poster_path: undefined,
        first_air_date: "2005-02-21",
        name: "Avatar: The Last Airbender",
        vote_average: 8.725,
        vote_count: 3883,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 35, 10765, 10759],
        id: 60625,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Rick and Morty",
        overview:
          "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
        popularity: 1412.945,
        poster_path: undefined,
        first_air_date: "2013-12-02",
        name: "Rick and Morty",
        vote_average: 8.698,
        vote_count: 9347,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [10759, 16, 10765, 35, 18],
        id: 31911,
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "鋼の錬金術師 FULLMETAL ALCHEMIST",
        overview:
          "Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.",
        popularity: 1438.097,
        poster_path: undefined,
        first_air_date: "2009-04-05",
        name: "Fullmetal Alchemist: Brotherhood",
        vote_average: 8.7,
        vote_count: 1914,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 10765],
        id: 218230,
        origin_country: ["KR"],
        original_language: "ko",
        original_name: "이재, 곧 죽습니다",
        overview:
          "At the brink of going to hell, Yee-jae must cycle through twelve separate lives and twelve separate deaths in this reincarnation drama.",
        popularity: 129.656,
        poster_path: undefined,
        first_air_date: "2023-12-15",
        name: "Death's Game",
        vote_average: 8.69,
        vote_count: 228,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 10751],
        id: 70785,
        origin_country: ["CA"],
        original_language: "en",
        original_name: "Anne with an E",
        overview:
          "A coming-of-age story about an outsider who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.",
        popularity: 227.047,
        poster_path: undefined,
        first_air_date: "2017-03-19",
        name: "Anne with an E",
        vote_average: 8.682,
        vote_count: 4533,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10759, 10765],
        id: 85937,
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "鬼滅の刃",
        overview:
          "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.",
        popularity: 139.646,
        poster_path: undefined,
        first_air_date: "2019-04-06",
        name: "Demon Slayer: Kimetsu no Yaiba",
        vote_average: 8.672,
        vote_count: 5985,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [80, 18],
        id: 60059,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Better Call Saul",
        overview:
          'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
        popularity: 825.58,
        poster_path: undefined,
        first_air_date: "2015-02-08",
        name: "Better Call Saul",
        vote_average: 8.67,
        vote_count: 4838,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18],
        id: 87108,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Chernobyl",
        overview:
          "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
        popularity: 371.854,
        poster_path: undefined,
        first_air_date: "2019-05-06",
        name: "Chernobyl",
        vote_average: 8.666,
        vote_count: 5885,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [10759, 10765, 16],
        id: 127532,
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "俺だけレベルアップな件",
        overview:
          "They say whatever doesn’t kill you makes you stronger, but that’s not the case for the world’s weakest hunter Sung Jinwoo. After being brutally slaughtered by monsters in a high-ranking dungeon, Jinwoo came back with the System, a program only he could see, that’s leveling him up in every way. Now, he’s inspired to discover the secrets behind his powers and the dungeon that spawned them.",
        popularity: 400.897,
        poster_path: undefined,
        first_air_date: "2024-01-07",
        name: "Solo Leveling",
        vote_average: 8.664,
        vote_count: 290,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10765, 10759],
        id: 1429,
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "進撃の巨人",
        overview:
          "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
        popularity: 234.212,
        poster_path: undefined,
        first_air_date: "2013-04-07",
        name: "Attack on Titan",
        vote_average: 8.664,
        vote_count: 6025,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10765, 10759, 18],
        id: 95557,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Invincible",
        overview:
          "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.",
        popularity: 633.221,
        poster_path: undefined,
        first_air_date: "2021-03-25",
        name: "Invincible",
        vote_average: 8.663,
        vote_count: 4210,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 35, 18, 10759],
        id: 42705,
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "はじめの一歩",
        overview:
          "Makunouchi Ippo is an ordinary high school student in Japan. Since he spends most of his time away from school helping his mother run the family business, he doesn't get to enjoy his younger years like most teenagers. Always a target for bullying at school (the family fishing business grants him a distinct odor), Ippo's life is one of hardship. One of these after-school bullying sessions turns Ippo's life around for the better, as he is saved by a boxer named Takamura. He decides to follow in Takamura's footsteps and train to become a boxer, giving his life direction and purpose. Ippo's path to perfecting his pugilistic prowess is just beginning...",
        popularity: 342.631,
        poster_path: undefined,
        first_air_date: "2000-10-03",
        name: "Fighting Spirit",
        vote_average: 8.653,
        vote_count: 965,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10765, 18, 10759, 35],
        id: 92685,
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Owl House",
        overview:
          "An animated fantasy-comedy series that follows Luz, a self-assured teenage girl who accidentally stumbles upon a portal to a magical world where she befriends a rebellious witch, Eda, and an adorably tiny warrior, King. Despite not having magical abilities, Luz pursues her dream of becoming a witch by serving as Eda's apprentice at the Owl House and ultimately finds a new family in an unlikely setting.",
        popularity: 319.585,
        poster_path: undefined,
        first_air_date: "2020-01-10",
        name: "The Owl House",
        vote_average: 8.7,
        vote_count: 1509,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 10765, 35],
        id: 67915,
        origin_country: ["KR"],
        original_language: "ko",
        original_name: "쓸쓸하고 찬란하神-도깨비",
        overview:
          "In his quest for a bride to break his immortal curse, a 939-year-old guardian of souls meets a grim reaper and a sprightly student with a tragic past.",
        popularity: 111.33,
        poster_path: undefined,
        first_air_date: "2016-12-02",
        name: "Goblin",
        vote_average: 8.657,
        vote_count: 2630,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [18, 10751],
        id: 85077,
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Chosen",
        overview:
          "The life of Christ through the eyes of those who encountered him called The Chosen.",
        popularity: 348.542,
        poster_path: undefined,
        first_air_date: "2019-04-21",
        name: "The Chosen",
        vote_average: 8.655,
        vote_count: 281,
      },
      {
        adult: false,
        backdrop_path: undefined,
        genre_ids: [16, 10762, 35],
        id: 82728,
        origin_country: ["AU"],
        original_language: "en",
        original_name: "Bluey",
        overview:
          "Bluey is an inexhaustible six year-old Blue Heeler dog, who loves to play and turns everyday family life into extraordinary adventures, developing her imagination as well as her mental, physical and emotional resilience.",
        popularity: 1022.266,
        poster_path: undefined,
        first_air_date: "2018-10-01",
        name: "Bluey",
        vote_average: 8.655,
        vote_count: 458,
      },
    ],
  },
};
