export const hotMovies = [
  {
    backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
    id: 693134,
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Dune: Part Two",
    original_language: "en",
    genre_ids: [878, 12],
    popularity: 1664.628,
    release_date: "2024-02-27",
    video: false,
    vote_average: 8.266,
    vote_count: 3418,
  },
  {
    backdrop_path: "/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg",
    id: 934632,
    original_title: "Rebel Moon — Part Two: The Scargiver",
    overview:
      "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Rebel Moon — Part Two: The Scargiver",
    original_language: "en",
    genre_ids: [878, 28, 18, 12],
    popularity: 2230.49,
    release_date: "2024-04-19",
    video: false,
    vote_average: 6.13,
    vote_count: 516,
  },
  {
    backdrop_path: "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
    id: 560016,
    original_title: "Monkey Man",
    overview:
      "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Monkey Man",
    original_language: "en",
    genre_ids: [28, 53, 80],
    popularity: 488.484,
    release_date: "2024-04-03",
    video: false,
    vote_average: 7.4,
    vote_count: 225,
  },
  {
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    id: 438631,
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Dune",
    original_language: "en",
    genre_ids: [878, 12],
    popularity: 530.126,
    release_date: "2021-09-15",
    video: false,
    vote_average: 7.79,
    vote_count: 11421,
  },
  {
    backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
    id: 1011985,
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Kung Fu Panda 4",
    original_language: "en",
    genre_ids: [16, 28, 10751, 35, 14],
    popularity: 1749.807,
    release_date: "2024-03-02",
    video: false,
    vote_average: 7.163,
    vote_count: 1347,
  },
  {
    backdrop_path: "/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg",
    id: 929590,
    original_title: "Civil War",
    overview:
      "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Civil War",
    original_language: "en",
    genre_ids: [10752, 28, 18],
    popularity: 622.204,
    release_date: "2024-04-10",
    video: false,
    vote_average: 7.412,
    vote_count: 455,
  },
  {
    backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
    id: 937287,
    original_title: "Challengers",
    overview:
      'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Challengers",
    original_language: "en",
    genre_ids: [18, 10749],
    popularity: 455.371,
    release_date: "2024-04-18",
    video: false,
    vote_average: 7.414,
    vote_count: 157,
  },
  {
    backdrop_path: "/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg",
    id: 967847,
    original_title: "Ghostbusters: Frozen Empire",
    overview:
      "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Ghostbusters: Frozen Empire",
    original_language: "en",
    genre_ids: [14, 12, 35],
    popularity: 398.503,
    release_date: "2024-03-20",
    video: false,
    vote_average: 6.42,
    vote_count: 343,
  },
  {
    backdrop_path: "/aINel9503ompOlGKn4sIVMg09Un.jpg",
    id: 838209,
    original_title: "파묘",
    overview:
      "After tracing the origin of a disturbing supernatural affliction to a wealthy family's ancestral gravesite, a team of paranormal experts relocates the remains—and soon discovers what happens to those who dare to mess with the wrong grave.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Exhuma",
    original_language: "ko",
    genre_ids: [9648, 27, 53],
    popularity: 399.782,
    release_date: "2024-02-22",
    video: false,
    vote_average: 7.796,
    vote_count: 54,
  },
  {
    backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
    id: 866398,
    original_title: "The Beekeeper",
    overview:
      "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "The Beekeeper",
    original_language: "en",
    genre_ids: [28, 53, 18],
    popularity: 467.217,
    release_date: "2024-01-08",
    video: false,
    vote_average: 7.462,
    vote_count: 2160,
  },
  {
    backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
    id: 618588,
    original_title: "Arthur the King",
    overview:
      "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Arthur the King",
    original_language: "en",
    genre_ids: [18, 12],
    popularity: 1016.256,
    release_date: "2024-03-15",
    video: false,
    vote_average: 6.763,
    vote_count: 57,
  },
  {
    backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
    id: 1041613,
    original_title: "Immaculate",
    overview:
      "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Immaculate",
    original_language: "en",
    genre_ids: [27, 9648, 53],
    popularity: 1325.513,
    release_date: "2024-03-20",
    video: false,
    vote_average: 6.208,
    vote_count: 300,
  },
  {
    backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
    id: 938614,
    original_title: "Late Night with the Devil",
    overview:
      "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Late Night with the Devil",
    original_language: "en",
    genre_ids: [27],
    popularity: 737.162,
    release_date: "2024-03-19",
    video: false,
    vote_average: 7.308,
    vote_count: 221,
  },
  {
    backdrop_path: "/qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg",
    id: 845111,
    original_title: "Les trois mousquetaires : Milady",
    overview:
      "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "The Three Musketeers: Milady",
    original_language: "fr",
    genre_ids: [12, 28, 18],
    popularity: 1155.119,
    release_date: "2023-12-13",
    video: false,
    vote_average: 6.524,
    vote_count: 340,
  },
  {
    backdrop_path: "/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg",
    id: 948549,
    original_title: "Love Lies Bleeding",
    overview:
      "Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Love Lies Bleeding",
    original_language: "en",
    genre_ids: [80, 10749, 53],
    popularity: 173.866,
    release_date: "2024-03-08",
    video: false,
    vote_average: 7.136,
    vote_count: 77,
  },
  {
    backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
    id: 823464,
    original_title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Godzilla x Kong: The New Empire",
    original_language: "en",
    genre_ids: [28, 878, 12],
    popularity: 2119.822,
    release_date: "2024-03-27",
    video: false,
    vote_average: 6.638,
    vote_count: 781,
  },
  {
    backdrop_path: "/sRLC052ieEzkQs9dEtPMfFxYkej.jpg",
    id: 848326,
    original_title: "Rebel Moon — Part One: A Child of Fire",
    overview:
      "When the ruthless forces of the Motherworld threaten a quiet farming village on a distant moon, a mysterious outsider becomes its best hope for survival.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Rebel Moon — Part One: A Child of Fire",
    original_language: "en",
    genre_ids: [878, 18, 28],
    popularity: 313.395,
    release_date: "2023-12-15",
    video: false,
    vote_average: 6.369,
    vote_count: 1748,
  },
  {
    backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
    id: 1111873,
    original_title: "Abigail",
    overview:
      "After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Abigail",
    original_language: "en",
    genre_ids: [27, 53, 35],
    popularity: 397.803,
    release_date: "2024-04-18",
    video: false,
    vote_average: 6.761,
    vote_count: 67,
  },
  {
    backdrop_path: "/cJiZwrwHiU9edbHEDDqCsna0xtS.jpg",
    id: 533535,
    original_title: "Deadpool \u0026 Wolverine",
    overview: 'Third entry in the "Deadpool" franchise. Plot TBA.',
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Deadpool \u0026 Wolverine",
    original_language: "en",
    genre_ids: [35, 878, 28],
    popularity: 341.963,
    release_date: "2024-07-24",
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    backdrop_path: "/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg",
    id: 1209288,
    original_title: "Justice League: Crisis on Infinite Earths Part Two",
    overview:
      "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?",
    poster_path: undefined,
    media_type: "movie",
    adult: false,
    title: "Justice League: Crisis on Infinite Earths Part Two",
    original_language: "en",
    genre_ids: [16, 878, 28],
    popularity: 564.647,
    release_date: "2024-04-22",
    video: false,
    vote_average: 6.3,
    vote_count: 31,
  },
];
