export const movieInfos = {
  default: true,
  adult: false,
  backdrop_path: undefined,
  created_by: [
    {
      id: 1612453,
      credit_id: "636d3c80f14dad007b260c70",
      name: "Geneva Robertson-Dworet",
      original_name: "Geneva Robertson-Dworet",
      gender: 1,
      profile_path: undefined,
    },
    {
      id: 1807680,
      credit_id: "636d3c8d8138310080844843",
      name: "Graham Wagner",
      original_name: "Graham Wagner",
      gender: 2,
      profile_path: null,
    },
  ],
  episode_run_time: [],
  first_air_date: undefined,
  genres: [
    {
      id: 10759,
      name: "Action & Adventure",
    },
    {
      id: 10765,
      name: "Sci-Fi & Fantasy",
    },
    {
      id: 9648,
      name: "Mystery",
    },
  ],
  homepage: "https://www.amazon.com/dp/B0CN4HV16N",
  id: 106379,
  in_production: true,
  languages: ["tl", "en"],
  last_air_date: "2024-04-10",
  last_episode_to_air: {
    id: 5197538,
    overview: "War…",
    name: "The Beginning",
    vote_average: 7.917,
    vote_count: 18,
    air_date: "2024-04-10",
    episode_number: 8,
    episode_type: "finale",
    production_code: "HNDO 108",
    runtime: 63,
    season_number: 1,
    show_id: 106379,
    still_path: undefined,
  },
  name: "Fallout",
  next_episode_to_air: null,
  networks: [
    {
      id: 1024,
      logo_path: undefined,
      name: "Prime Video",
      origin_country: "",
    },
  ],
  number_of_episodes: 8,
  number_of_seasons: 1,
  origin_country: ["US"],
  original_language: "en",
  original_name: undefined,
  overview: undefined,
  popularity: 1835.873,
  poster_path: undefined,
  production_companies: [
    {
      id: 103490,
      logo_path: undefined,
      name: "Kilter Films",
      origin_country: "US",
    },
    {
      id: 137613,
      logo_path: undefined,
      name: "Bethesda Game Studios",
      origin_country: "US",
    },
    {
      id: 210099,
      logo_path: undefined,
      name: "Amazon MGM Studios",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  seasons: [
    {
      air_date: "2024-04-10",
      episode_count: 8,
      id: 157128,
      name: "Season 1",
      overview: "",
      poster_path: undefined,
      season_number: 1,
      vote_average: 7.7,
    },
  ],
  spoken_languages: [
    {
      english_name: "Tagalog",
      iso_639_1: "tl",
      name: "",
    },
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Returning Series",
  tagline: "The world deserves a better ending.",
  type: "Scripted",
  vote_average: 8.4,
  vote_count: 705,
  videos: {
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Ella Purnell was just a little jealous of Aaron Moten's Fallout Power Armour",
        key: "PpbFSjMZcbs",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-04-09T14:30:09.000Z",
        id: "6616ddf3d6590b017ea5c1fe",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Prepare for Fallout with Prime",
        key: "a1V0hWRh_Ys",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-04-05T18:30:00.000Z",
        id: "6610e403c68b69016303b1c3",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Console to Camera",
        key: "4iZl7Ncyyhg",
        site: "YouTube",
        size: 1080,
        type: "Behind the Scenes",
        official: true,
        published_at: "2024-04-05T18:00:02.000Z",
        id: "6610e416d768fe017b41f127",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "The World Of Featurette",
        key: "qljE3C6Gn18",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-04-02T18:00:20.000Z",
        id: "6610c8575b370d014a63a53f",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Slice of Pie with Ella and Kyle",
        key: "8K02U0z8lJY",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-03-29T16:00:10.000Z",
        id: "6607ac2dd5191f017e30a79b",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "End Times (Vertical)",
        key: "3_BgWJWnUyM",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-03-28T23:17:03.000Z",
        id: "6610c866df86a8016452f1d9",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "What Would You Take Into The Vault?",
        key: "2z5s-V_yfiw",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-03-28T17:00:01.000Z",
        id: "6607ac21283ed9017c1a066d",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Fallout 101 with The Cast",
        key: "WwgYj_WoirE",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-03-27T20:00:14.000Z",
        id: "66053d88aafebd018717de4c",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "New World",
        key: "2kenZdzuUFw",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-03-19T21:20:44.000Z",
        id: "6610c8446f43ec017dc14651",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "End Times",
        key: "u_JW8JztIXA",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-03-19T21:20:40.000Z",
        id: "660cbb8e0b5fd6017c38a501",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "First Scene",
        key: "Z_7jXPMu0Nk",
        site: "YouTube",
        size: 1080,
        type: "Clip",
        official: true,
        published_at: "2024-03-19T14:30:17.000Z",
        id: "65fa20332476f2017c1444f5",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Why Walton Goggins Sweats Out of His Eyes on “Fallout”",
        key: "xRWSeql1ITY",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: false,
        published_at: "2024-03-09T03:30:30.000Z",
        id: "65ecc9f38cfcc70164621db2",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "V-mugKDQDlg",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2024-03-07T14:00:18.000Z",
        id: "65e9cd0972c13e0185c507f7",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Teaser Trailer",
        key: "0kQ8i2FpRDk",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2023-12-02T16:25:08.000Z",
        id: "656b5dc788634800c9e0e0dd",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Beyond The Game",
        key: "JbFMuQeHxnM",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2022-10-28T18:59:49.000Z",
        id: "635d92ba8289a00081bdbd6b",
      },
    ],
  },
  credits: {
    cast: [
      {
        adult: false,
        gender: 1,
        id: 989325,
        known_for_department: "Acting",
        name: "Ella Purnell",
        original_name: "Ella Purnell",
        popularity: 222.549,
        profile_path: undefined,
        character: "Lucy MacLean",
        credit_id: "6244b9ef9451e7005e7d3f49",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 1386221,
        known_for_department: "Acting",
        name: "Aaron Moten",
        original_name: "Aaron Moten",
        popularity: 40.678,
        profile_path: undefined,
        character: "Maximus",
        credit_id: "62bb56f894631800506f51bc",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 57412,
        known_for_department: "Acting",
        name: "Moisés Arias",
        original_name: "Moisés Arias",
        popularity: 48.48,
        profile_path: undefined,
        character: "Norman 'Norm' MacLean",
        credit_id: "65ebdea25bce9e0149465351",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 27740,
        known_for_department: "Acting",
        name: "Walton Goggins",
        original_name: "Walton Goggins",
        popularity: 64.206,
        profile_path: undefined,
        character: "The Ghoul / Cooper Howard",
        credit_id: "620ff2f9e0ca7f006aca85e4",
        order: 3,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 527,
        known_for_department: "Writing",
        name: "Jonathan Nolan",
        original_name: "Jonathan Nolan",
        popularity: 31.356,
        profile_path: undefined,
        credit_id: "5f19a187447f9c003636f66b",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 1464120,
        known_for_department: "Production",
        name: "Athena Wickham",
        original_name: "Athena Wickham",
        popularity: 6.905,
        profile_path: undefined,
        credit_id: "5f19a19f447f9c003636f705",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 588616,
        known_for_department: "Production",
        name: "Todd Howard",
        original_name: "Todd Howard",
        popularity: 4.464,
        profile_path: undefined,
        credit_id: "5f19a1c0abdafc00374d1a7d",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 1497967,
        known_for_department: "Writing",
        name: "Lisa Joy",
        original_name: "Lisa Joy",
        popularity: 12.619,
        profile_path: undefined,
        credit_id: "5f19a150abdafc00364d8464",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 2720519,
        known_for_department: "Production",
        name: "James Altman",
        original_name: "James Altman",
        popularity: 2.316,
        profile_path: undefined,
        credit_id: "5f19a1b3c1ffbd0034709965",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 1612453,
        known_for_department: "Writing",
        name: "Geneva Robertson-Dworet",
        original_name: "Geneva Robertson-Dworet",
        popularity: 19.93,
        profile_path: undefined,
        credit_id: "61d77d81e10f46008e7a879c",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 1807680,
        known_for_department: "Writing",
        name: "Graham Wagner",
        original_name: "Graham Wagner",
        popularity: 24.813,
        profile_path: null,
        credit_id: "61d77d942d1e4000425680d5",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 9041,
        known_for_department: "Art",
        name: "Howard Cummings",
        original_name: "Howard Cummings",
        popularity: 6.057,
        profile_path: null,
        credit_id: "63ef339145765d00792edc95",
        department: "Art",
        job: "Production Design",
      },
      {
        adult: false,
        gender: 1,
        id: 957661,
        known_for_department: "Art",
        name: "Regina Graves",
        original_name: "Regina Graves",
        popularity: 4.836,
        profile_path: null,
        credit_id: "63ef348235818f00bc0d963d",
        department: "Art",
        job: "Set Decoration",
      },
      {
        adult: false,
        gender: 1,
        id: 1190648,
        known_for_department: "Costume & Make-Up",
        name: "Amy Westcott",
        original_name: "Amy Westcott",
        popularity: 5.436,
        profile_path: undefined,
        credit_id: "65373e6685b10500c7bd4fae",
        department: "Costume & Make-Up",
        job: "Costume Design",
      },
      {
        adult: false,
        gender: 2,
        id: 10851,
        known_for_department: "Sound",
        name: "Ramin Djawadi",
        original_name: "Ramin Djawadi",
        popularity: 13.489,
        profile_path: undefined,
        credit_id: "65968b9360c51d7d659787a6",
        department: "Sound",
        job: "Original Music Composer",
      },
      {
        adult: false,
        gender: 1,
        id: 1123421,
        known_for_department: "Production",
        name: "Margot Lulick",
        original_name: "Margot Lulick",
        popularity: 2.898,
        profile_path: null,
        credit_id: "66175670c072a2017c9338bd",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 48070,
        known_for_department: "Editing",
        name: "Stephen Semel",
        original_name: "Stephen Semel",
        popularity: 3.735,
        profile_path: null,
        credit_id: "661756927e12f00163f163a0",
        department: "Production",
        job: "Co-Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1229794,
        known_for_department: "Writing",
        name: "Karey Dornetto",
        original_name: "Karey Dornetto",
        popularity: 5.153,
        profile_path: undefined,
        credit_id: "661756aa1fd36f017caccede",
        department: "Production",
        job: "Co-Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 1122300,
        known_for_department: "Directing",
        name: "Carson D. Mell",
        original_name: "Carson D. Mell",
        popularity: 3.676,
        profile_path: null,
        credit_id: "661756ca4539d00131fbde7b",
        department: "Production",
        job: "Co-Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 1291827,
        known_for_department: "Writing",
        name: "Kieran Fitzgerald",
        original_name: "Kieran Fitzgerald",
        popularity: 8.537,
        profile_path: undefined,
        credit_id: "661756fc0a517c017dff91e1",
        department: "Production",
        job: "Co-Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 561,
        known_for_department: "Production",
        name: "John Papsidera",
        original_name: "John Papsidera",
        popularity: 10.538,
        profile_path: undefined,
        credit_id: "6617573ed133240163e3f8a6",
        department: "Production",
        job: "Casting",
      },
      {
        adult: false,
        gender: 1,
        id: 1790518,
        known_for_department: "Production",
        name: "Kim Winther",
        original_name: "Kim Winther",
        popularity: 3.139,
        profile_path: null,
        credit_id: "6617574cd133240163e3f8b9",
        department: "Production",
        job: "Casting",
      },
      {
        adult: false,
        gender: 0,
        id: 1747687,
        known_for_department: "Visual Effects",
        name: "Jay Worth",
        original_name: "Jay Worth",
        popularity: 2.461,
        profile_path: null,
        credit_id: "661757e3f36a320163f9091e",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1237515,
        known_for_department: "Production",
        name: "Noreen O'Toole",
        original_name: "Noreen O'Toole",
        popularity: 2.101,
        profile_path: null,
        credit_id: "6617596b7e12f00163f16647",
        department: "Production",
        job: "Supervising Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1747687,
        known_for_department: "Visual Effects",
        name: "Jay Worth",
        original_name: "Jay Worth",
        popularity: 2.461,
        profile_path: null,
        credit_id: "661759756b5fc201632833eb",
        department: "Production",
        job: "Supervising Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 2661449,
        known_for_department: "Production",
        name: "Crystal Whelan",
        original_name: "Crystal Whelan",
        popularity: 1.851,
        profile_path: null,
        credit_id: "661759826b5fc201632833fb",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 2028344,
        known_for_department: "Production",
        name: "Halle Phillips",
        original_name: "Halle Phillips",
        popularity: 1.857,
        profile_path: null,
        credit_id: "6617598c1fd36f017cacd218",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 2301155,
        known_for_department: "Writing",
        name: "Gursimran Sandhu",
        original_name: "Gursimran Sandhu",
        popularity: 3.924,
        profile_path: null,
        credit_id: "6617599ce8a3e10149a0f4b2",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 3405354,
        known_for_department: "Acting",
        name: "Emil Pagliarulo",
        original_name: "Emil Pagliarulo",
        popularity: 1.312,
        profile_path: null,
        credit_id: "661759a97e12f0017cf197c9",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 4646496,
        known_for_department: "Production",
        name: "Istvan Pely",
        original_name: "Istvan Pely",
        popularity: 1.676,
        profile_path: null,
        credit_id: "661759bbd133240149e3c8dd",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 9041,
        known_for_department: "Art",
        name: "Howard Cummings",
        original_name: "Howard Cummings",
        popularity: 6.057,
        profile_path: null,
        credit_id: "66175a640a517c0163ff6a01",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 4646502,
        known_for_department: "Production",
        name: "Tara Shivkumar",
        original_name: "Tara Shivkumar",
        popularity: 1.012,
        profile_path: null,
        credit_id: "66175a82d133240163e3fb70",
        department: "Production",
        job: "Associate Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 4646503,
        known_for_department: "Writing",
        name: "Chaz Hawkins",
        original_name: "Chaz Hawkins",
        popularity: 2.431,
        profile_path: null,
        credit_id: "66175b1ec072a2014992e7cd",
        department: "Writing",
        job: "Executive Story Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 4646508,
        known_for_department: "Visual Effects",
        name: "Andrea Knoll",
        original_name: "Andrea Knoll",
        popularity: 1.453,
        profile_path: null,
        credit_id: "66175bddf36a32017df930d7",
        department: "Visual Effects",
        job: "Visual Effects Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1484972,
        known_for_department: "Sound",
        name: "Christopher Kaller",
        original_name: "Christopher Kaller",
        popularity: 3.396,
        profile_path: null,
        credit_id: "66175bee1fd36f017cacd4dd",
        department: "Sound",
        job: "Music Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 1364427,
        known_for_department: "Sound",
        name: "Clint Bennett",
        original_name: "Clint Bennett",
        popularity: 3.176,
        profile_path: null,
        credit_id: "66175bf87d41aa017d003f01",
        department: "Sound",
        job: "Music Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 1814699,
        known_for_department: "Sound",
        name: "Trygge Toven",
        original_name: "Trygge Toven",
        popularity: 3.761,
        profile_path: null,
        credit_id: "66175c027d41aa017d003f0e",
        department: "Sound",
        job: "Music Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 2047642,
        known_for_department: "Production",
        name: "Morgan Shaw",
        original_name: "Morgan Shaw",
        popularity: 0.84,
        profile_path: null,
        credit_id: "6617603d4d23dd014a6453d3",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 4646508,
        known_for_department: "Visual Effects",
        name: "Andrea Knoll",
        original_name: "Andrea Knoll",
        popularity: 1.453,
        profile_path: null,
        credit_id: "66176050d133240186e42873",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 2494684,
        known_for_department: "Art",
        name: "Ann Bartek",
        original_name: "Ann Bartek",
        popularity: 2.197,
        profile_path: null,
        credit_id: "661ab16769eb900149b78c90",
        department: "Art",
        job: "Art Direction",
      },
    ],
  },
  images: {
    backdrops: [
      {
        aspect_ratio: 1.778,
        height: 2160,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.384,
        vote_count: 2,
        width: 3840,
      },
      {
        aspect_ratio: 1.778,
        height: 2160,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.238,
        vote_count: 0,
        width: 3840,
      },
      {
        aspect_ratio: 1.778,
        height: 1440,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.172,
        vote_count: 1,
        width: 2560,
      },
      {
        aspect_ratio: 1.778,
        height: 1080,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.172,
        vote_count: 1,
        width: 1920,
      },
      {
        aspect_ratio: 1.778,
        height: 1440,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 0,
        vote_count: 0,
        width: 2560,
      },
      {
        aspect_ratio: 1.778,
        height: 2160,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 0,
        vote_count: 0,
        width: 3840,
      },
      {
        aspect_ratio: 1.778,
        height: 1440,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 0,
        vote_count: 0,
        width: 2560,
      },
      {
        aspect_ratio: 1.778,
        height: 2160,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 0,
        vote_count: 0,
        width: 3840,
      },
      {
        aspect_ratio: 1.777,
        height: 1810,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 0,
        vote_count: 0,
        width: 3217,
      },
    ],
    logos: [
      {
        aspect_ratio: 2.505,
        height: 4791,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.588,
        vote_count: 5,
        width: 12000,
      },
      {
        aspect_ratio: 2.505,
        height: 4791,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.384,
        vote_count: 2,
        width: 12000,
      },
      {
        aspect_ratio: 2.505,
        height: 4791,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.312,
        vote_count: 1,
        width: 12000,
      },
      {
        aspect_ratio: 2.504,
        height: 560,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.258,
        vote_count: 6,
        width: 1402,
      },
      {
        aspect_ratio: 2.505,
        height: 1197,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.258,
        vote_count: 6,
        width: 2999,
      },
      {
        aspect_ratio: 2.505,
        height: 1197,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.172,
        vote_count: 1,
        width: 2999,
      },
      {
        aspect_ratio: 2.505,
        height: 1197,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 2999,
      },
    ],
    posters: [
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.456,
        vote_count: 11,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.636,
        vote_count: 41,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.312,
        vote_count: 1,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.268,
        vote_count: 31,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.246,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.246,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.246,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.218,
        vote_count: 30,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 1350,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.19,
        vote_count: 5,
        width: 900,
      },
      {
        aspect_ratio: 0.667,
        height: 1350,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.19,
        vote_count: 5,
        width: 900,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.178,
        vote_count: 33,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 1500,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.172,
        vote_count: 1,
        width: 1000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.172,
        vote_count: 1,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.172,
        vote_count: 1,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.164,
        vote_count: 14,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 1350,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.128,
        vote_count: 6,
        width: 900,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.12,
        vote_count: 17,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 1350,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 900,
      },
      {
        aspect_ratio: 0.667,
        height: 1500,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 1000,
      },
      {
        aspect_ratio: 0.667,
        height: 1500,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 1000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.106,
        vote_count: 2,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.1,
        vote_count: 13,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.044,
        vote_count: 3,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.044,
        vote_count: 3,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 5.044,
        vote_count: 3,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 4.982,
        vote_count: 4,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 4.982,
        vote_count: 4,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 4.982,
        vote_count: 4,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 4.882,
        vote_count: 8,
        width: 2000,
      },
      {
        aspect_ratio: 0.667,
        height: 3000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 0,
        vote_count: 0,
        width: 2000,
      },
      {
        aspect_ratio: 0.68,
        height: 1000,
        iso_639_1: "en",
        file_path: undefined,
        vote_average: 0,
        vote_count: 0,
        width: 680,
      },
    ],
  },
  external_ids: {
    imdb_id: "tt12637874",
    freebase_mid: null,
    freebase_id: null,
    tvdb_id: 416744,
    tvrage_id: null,
    wikidata_id: "Q113127312",
    facebook_id: null,
    instagram_id: "falloutonprime",
    twitter_id: "falloutonprime",
  },
};
